// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: msg.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO msgs (id, created_at, updated_at, message)
VALUES (
    $1,
    $2,
    $3,
    $4
    )
RETURNING id, created_at, updated_at, message
`

type CreateMessageParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Message   string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Msg, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Message,
	)
	var i Msg
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Message,
	)
	return i, err
}
